# Generated by Django 2.0.7 on 2019-07-15 13:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductPrice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Helpful title for differentiating prices', max_length=200)),
                ('price', models.PositiveIntegerField(help_text='Price of products in cents')),
                ('date_start', models.DateField()),
                ('date_end', models.DateField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='new_product_price', to='products.Product')),
            ],
        ),
    ]
